import { useState, useEffect } from 'react'
import { QRCodeCanvas } from 'qrcode.react'
import {
  Box,
  Container,
  Typography,
  Card,
  CardContent,
  TextField,
  Button,
  Grid,
  IconButton,
  Alert,
  CircularProgress,
  Chip,
  Divider,
  Switch,
  FormControlLabel,
  Paper,
} from '@mui/material'
import {
  Add,
  Delete,
  Restaurant,
  AutoAwesome,
  CheckCircle,
  Search,
} from '@mui/icons-material'
import { menuGenerationApi, menuApi } from '@services/api'
import type {
  MenuCategoryCreate,
  MenuItemCreate,
  MenuGenerationResponse,
} from '@types/index'

// 메뉴 아이템 이미지 컴포넌트 (이미지 로딩 상태 관리)
function MenuItemImage({ imageUrl, menuName }: { imageUrl?: string | null; menuName: string }) {
  const [imageLoaded, setImageLoaded] = useState(false)
  const [imageError, setImageError] = useState(false)

  if (!imageUrl) {
    return (
      <Box
        sx={{
          width: 200,
          height: 200,
          backgroundColor: 'grey.200',
          borderRadius: 2,
          flexShrink: 0,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
        }}
      >
        <Restaurant sx={{ fontSize: 64, color: 'grey.400' }} />
      </Box>
    )
  }

  return (
    <Box sx={{ position: 'relative', width: 200, height: 200, flexShrink: 0 }}>
      {/* 이미지 로딩 중 표시 */}
      {!imageLoaded && !imageError && (
        <Box
          sx={{
            position: 'absolute',
            width: 200,
            height: 200,
            backgroundColor: 'grey.200',
            borderRadius: 2,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            flexDirection: 'column',
            gap: 1,
          }}
        >
          <CircularProgress size={40} />
          <Typography variant="caption" color="text.secondary">
            이미지 로딩 중...
          </Typography>
        </Box>
      )}

      {/* 실제 이미지 */}
      <Box
        component="img"
        src={imageUrl}
        alt={menuName}
        onLoad={() => setImageLoaded(true)}
        onError={() => setImageError(true)}
        sx={{
          width: 200,
          height: 200,
          objectFit: 'cover',
          borderRadius: 2,
          boxShadow: 2,
          display: imageLoaded ? 'block' : 'none',
        }}
      />

      {/* 이미지 로드 실패 */}
      {imageError && (
        <Box
          sx={{
            position: 'absolute',
            width: 200,
            height: 200,
            backgroundColor: 'grey.200',
            borderRadius: 2,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
          }}
        >
          <Restaurant sx={{ fontSize: 64, color: 'grey.400' }} />
        </Box>
      )}
    </Box>
  )
}

// 디폴트 샘플 메뉴 (매장 ID 0번)
const DEFAULT_CATEGORIES: MenuCategoryCreate[] = [
  {
    category_name: '파스타',
    category_description: '',
    items: [
      { name: '로제파스타', price: 15000, ingredients: [] },
      { name: '토마토파스타', price: 15000, ingredients: [] },
      { name: '오일파스타', price: 15000, ingredients: [] },
    ],
  },
  {
    category_name: '스테이크',
    category_description: '',
    items: [
      { name: '채끝 스테이크', price: 33000, ingredients: [] },
      { name: '미니 스테이크', price: 15000, ingredients: [] },
    ],
  },
  {
    category_name: '음료',
    category_description: '',
    items: [
      { name: '사이다', price: 2000, ingredients: [] },
      { name: '콜라', price: 2000, ingredients: [] },
      { name: '제로콜라', price: 2000, ingredients: [] },
    ],
  },
  {
    category_name: '사이드',
    category_description: '',
    items: [
      { name: '감자튀김', price: 6000, ingredients: [] },
    ],
  },
]

function MenuGenerationPage() {
  // State
  const [storeId, setStoreId] = useState<string>('0')
  const [viewStoreId, setViewStoreId] = useState<string>('0')
  const [categories, setCategories] = useState<MenuCategoryCreate[]>(DEFAULT_CATEGORIES)
  const [autoGenerateImages, setAutoGenerateImages] = useState(true)
  const [autoGenerateDescriptions, setAutoGenerateDescriptions] = useState(true)
  const [isLoading, setIsLoading] = useState(false)
  const [isLoadingMenus, setIsLoadingMenus] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [result, setResult] = useState<MenuGenerationResponse | null>(null)
  const [displayMenus, setDisplayMenus] = useState<any>(null)
  const [generatedStoreId, setGeneratedStoreId] = useState<number | null>(null)

  // 카테고리 추가
  const handleAddCategory = () => {
    setCategories([
      ...categories,
      {
        category_name: '',
        category_description: '',
        items: [{ name: '', price: undefined, ingredients: [] }],
      },
    ])
  }

  // 카테고리 삭제
  const handleRemoveCategory = (categoryIndex: number) => {
    setCategories(categories.filter((_, index) => index !== categoryIndex))
  }

  // 카테고리 이름 변경
  const handleCategoryNameChange = (categoryIndex: number, value: string) => {
    const newCategories = [...categories]
    newCategories[categoryIndex].category_name = value
    setCategories(newCategories)
  }

  // 메뉴 아이템 추가
  const handleAddItem = (categoryIndex: number) => {
    const newCategories = [...categories]
    newCategories[categoryIndex].items.push({
      name: '',
      price: undefined,
      ingredients: [],
    })
    setCategories(newCategories)
  }

  // 메뉴 아이템 삭제
  const handleRemoveItem = (categoryIndex: number, itemIndex: number) => {
    const newCategories = [...categories]
    newCategories[categoryIndex].items = newCategories[categoryIndex].items.filter(
      (_, index) => index !== itemIndex
    )
    setCategories(newCategories)
  }

  // 메뉴 아이템 변경
  const handleItemChange = (
    categoryIndex: number,
    itemIndex: number,
    field: keyof MenuItemCreate,
    value: any
  ) => {
    const newCategories = [...categories]
    newCategories[categoryIndex].items[itemIndex] = {
      ...newCategories[categoryIndex].items[itemIndex],
      [field]: value,
    }
    setCategories(newCategories)
  }

  // 재료 추가
  const handleAddIngredient = (categoryIndex: number, itemIndex: number, ingredient: string) => {
    if (!ingredient.trim()) return

    const newCategories = [...categories]
    const currentIngredients = newCategories[categoryIndex].items[itemIndex].ingredients || []
    newCategories[categoryIndex].items[itemIndex].ingredients = [
      ...currentIngredients,
      ingredient.trim(),
    ]
    setCategories(newCategories)
  }

  // 재료 삭제
  const handleRemoveIngredient = (
    categoryIndex: number,
    itemIndex: number,
    ingredientIndex: number
  ) => {
    const newCategories = [...categories]
    const currentIngredients = newCategories[categoryIndex].items[itemIndex].ingredients || []
    newCategories[categoryIndex].items[itemIndex].ingredients = currentIngredients.filter(
      (_, index) => index !== ingredientIndex
    )
    setCategories(newCategories)
  }

  // 매장 메뉴 조회
  const handleLoadStoreMenus = async () => {
    const id = parseInt(viewStoreId)

    // 매장 ID 0: 디폴트 샘플 메뉴
    if (id === 0) {
      setDisplayMenus({
        categories: DEFAULT_CATEGORIES.map((cat, idx) => ({
          name: cat.category_name,
          description: cat.category_description,
          items: cat.items.map((item, itemIdx) => ({
            name: item.name,
            description: item.description,
            price: item.price,
            image_url: null,
            is_ai_generated_image: false,
            is_ai_generated_description: false,
          })),
        })),
      })
      // 입력 폼에도 샘플 메뉴 채우기
      setCategories(DEFAULT_CATEGORIES)
      setStoreId('0')
      setError(null)
      return
    }

    // 매장 ID 1 이상: DB에서 조회
    setIsLoadingMenus(true)
    setError(null)

    try {
      const response = await menuApi.getStoreMenus(id)

      if (response.data.categories.length === 0) {
        setError(`매장 ID ${id}번의 메뉴가 없습니다. 먼저 메뉴를 생성해주세요.`)
        setDisplayMenus(null)
        setCategories(DEFAULT_CATEGORIES)
      } else {
        // 조회된 메뉴를 displayMenus에 설정 (이미지 포함한 전체 정보)
        setDisplayMenus({ categories: response.data.categories })

        // 입력 폼에 기존 메뉴 채우기 (카테고리, 메뉴명, 가격, 재료만)
        const loadedCategories: MenuCategoryCreate[] = response.data.categories.map((cat: any) => ({
          category_name: cat.name,
          category_description: cat.description || '',
          items: cat.items.map((item: any) => ({
            name: item.name,
            price: item.price,
            description: undefined, // 설명은 AI가 다시 생성하도록
            image_url: undefined,   // 이미지는 AI가 다시 생성하도록
            ingredients: item.ingredients || []
          }))
        }))

        setCategories(loadedCategories)
        setStoreId(id.toString())
      }
    } catch (err: any) {
      setError(err.message || '메뉴 조회 중 오류가 발생했습니다.')
      setDisplayMenus(null)
      setCategories(DEFAULT_CATEGORIES)
    } finally {
      setIsLoadingMenus(false)
    }
  }

  // 메뉴판 생성
  const handleGenerate = async () => {
    const id = parseInt(storeId)

    if (id === 0) {
      setError('매장 ID 0번은 샘플 메뉴입니다. 1번부터 생성 가능합니다.')
      return
    }

    setIsLoading(true)
    setError(null)
    setResult(null)

    try {
      const response = await menuGenerationApi.generate({
        store_id: id,
        categories,
        auto_generate_images: autoGenerateImages,
        auto_generate_descriptions: autoGenerateDescriptions,
      })

      setResult(response)
      setGeneratedStoreId(id)
    } catch (err: any) {
      setError(err.message || '메뉴판 생성 중 오류가 발생했습니다.')
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <Container maxWidth="lg" sx={{ py: 4 }}>
      {/* 헤더 */}
      <Box sx={{ mb: 4, textAlign: 'center' }}>
        <Restaurant sx={{ fontSize: 48, color: 'primary.main', mb: 2 }} />
        <Typography variant="h3" gutterBottom fontWeight="bold">
          AI 메뉴판 생성
        </Typography>
        <Typography variant="h6" color="text.secondary">
          메뉴 카테고리와 아이템을 입력하면 AI가 자동으로 설명과 이미지를 생성합니다
        </Typography>
      </Box>

      {/* 매장 조회 */}
      <Card sx={{ mb: 2, bgcolor: 'primary.50' }}>
        <CardContent>
          <Typography variant="h6" gutterBottom>
            매장 조회
          </Typography>
          <Typography variant="body2" color="text.secondary" gutterBottom>
            매장 ID 0번: 샘플 메뉴판 / 1번 이상: 실제 생성된 메뉴판
          </Typography>
          <Grid container spacing={1.5} alignItems="center" sx={{ mt: 1 }}>
            <Grid item xs={12} sm={6} md={4}>
              <TextField
                fullWidth
                size="small"
                label="조회할 매장 ID"
                type="number"
                value={viewStoreId}
                onChange={(e) => setViewStoreId(e.target.value)}
              />
            </Grid>
            <Grid item xs={12} sm={6} md={4}>
              <Button
                variant="contained"
                fullWidth
                onClick={handleLoadStoreMenus}
                disabled={isLoadingMenus}
                startIcon={isLoadingMenus ? <CircularProgress size={20} /> : <Search />}
              >
                {isLoadingMenus ? '조회 중...' : '매장 조회'}
              </Button>
            </Grid>
          </Grid>
        </CardContent>
      </Card>

      {/* 매장 QR 코드 - 메뉴가 1개 이상 있을 때만 표시 */}
      {parseInt(viewStoreId) > 0 && displayMenus && displayMenus.categories && displayMenus.categories.length > 0 && (
        <Card sx={{ mb: 2, bgcolor: 'success.50' }}>
          <CardContent>
            <Box sx={{ textAlign: 'center' }}>
              <Typography variant="h6" fontWeight="bold" gutterBottom>
                매장 QR 코드
              </Typography>
              <Typography variant="body2" color="text.secondary" gutterBottom sx={{ mb: 2 }}>
                고객이 스캔할 수 있도록 QR 코드를 제공하세요
              </Typography>

              <Box sx={{ display: 'inline-block', p: 2, bgcolor: 'white', borderRadius: 2, boxShadow: 2 }}>
                <QRCodeCanvas
                  value={`${window.location.origin}/menu-board/${viewStoreId}`}
                  size={180}
                  level="H"
                />
              </Box>

              <Paper elevation={1} sx={{ p: 2, mt: 2, bgcolor: 'white' }}>
                <Typography variant="body2" color="text.secondary" gutterBottom>
                  AI 메뉴판 URL
                </Typography>
                <Typography
                  variant="body2"
                  sx={{
                    fontFamily: 'monospace',
                    wordBreak: 'break-all',
                    color: 'primary.main',
                    mb: 1
                  }}
                >
                  {window.location.origin}/menu-board/{viewStoreId}
                </Typography>
                <Button
                  variant="outlined"
                  size="small"
                  onClick={() => {
                    navigator.clipboard.writeText(`${window.location.origin}/menu-board/${viewStoreId}`)
                    alert('URL이 복사되었습니다!')
                  }}
                >
                  URL 복사
                </Button>
              </Paper>
            </Box>
          </CardContent>
        </Card>
      )}

      {/* 설정 */}
      <Card sx={{ mb: 2 }}>
        <CardContent>
          <Typography variant="h6" gutterBottom>
            메뉴 생성 설정
          </Typography>
          <Grid container spacing={1.5} alignItems="center">
            <Grid item xs={12} sm={4}>
              <TextField
                fullWidth
                size="small"
                label="생성할 매장 ID (1부터)"
                type="number"
                value={storeId}
                onChange={(e) => setStoreId(e.target.value)}
              />
            </Grid>
            <Grid item xs={12} sm={4}>
              <FormControlLabel
                control={
                  <Switch
                    checked={autoGenerateDescriptions}
                    onChange={(e) => setAutoGenerateDescriptions(e.target.checked)}
                  />
                }
                label="AI 설명 자동 생성"
              />
            </Grid>
            <Grid item xs={12} sm={4}>
              <FormControlLabel
                control={
                  <Switch
                    checked={autoGenerateImages}
                    onChange={(e) => setAutoGenerateImages(e.target.checked)}
                  />
                }
                label="AI 이미지 자동 생성"
              />
            </Grid>
          </Grid>
        </CardContent>
      </Card>

      {/* 카테고리 입력 */}
      {categories.map((category, categoryIndex) => (
        <Card key={categoryIndex} sx={{ mb: 2 }}>
          <CardContent>
            <Box sx={{ display: 'flex', alignItems: 'center', mb: 1.5 }}>
              <Typography variant="h6" sx={{ flexGrow: 1 }}>
                카테고리 {categoryIndex + 1}
              </Typography>
              {categories.length > 1 && (
                <IconButton
                  size="small"
                  color="error"
                  onClick={() => handleRemoveCategory(categoryIndex)}
                >
                  <Delete />
                </IconButton>
              )}
            </Box>

            <TextField
              fullWidth
              size="small"
              label="카테고리 이름 (예: 파스타, 스테이크)"
              value={category.category_name}
              onChange={(e) => handleCategoryNameChange(categoryIndex, e.target.value)}
              sx={{ mb: 1.5 }}
            />

            <Divider sx={{ my: 1.5 }} />

            {/* 메뉴 아이템 - Grid 레이아웃 (가로 3개씩) */}
            <Grid container spacing={1.5}>
              {category.items.map((item, itemIndex) => (
                <Grid item xs={12} sm={6} md={4} key={itemIndex}>
                  <Paper sx={{ p: 1.5, bgcolor: 'grey.50', height: '100%' }}>
                    <Box sx={{ display: 'flex', alignItems: 'center', mb: 1 }}>
                      <Typography variant="body2" fontWeight="bold" sx={{ flexGrow: 1 }}>
                        메뉴 {itemIndex + 1}
                      </Typography>
                      {category.items.length > 1 && (
                        <IconButton
                          size="small"
                          color="error"
                          onClick={() => handleRemoveItem(categoryIndex, itemIndex)}
                        >
                          <Delete />
                        </IconButton>
                      )}
                    </Box>

                    {/* 2열 레이아웃: 왼쪽 입력필드, 오른쪽 재료 Chip */}
                    <Box sx={{ display: 'flex', gap: 1 }}>
                      {/* 왼쪽: 입력 필드들 */}
                      <Box sx={{ flex: '0 0 55%', display: 'flex', flexDirection: 'column', gap: 1 }}>
                        <TextField
                          fullWidth
                          size="small"
                          label="메뉴 이름"
                          value={item.name}
                          onChange={(e) =>
                            handleItemChange(categoryIndex, itemIndex, 'name', e.target.value)
                          }
                          required
                        />

                        <TextField
                          fullWidth
                          size="small"
                          label="가격"
                          type="number"
                          value={item.price || ''}
                          onChange={(e) =>
                            handleItemChange(
                              categoryIndex,
                              itemIndex,
                              'price',
                              e.target.value ? parseFloat(e.target.value) : undefined
                            )
                          }
                        />

                        <Box>
                          <Typography variant="caption" color="text.secondary">
                            재료
                          </Typography>
                          <TextField
                            fullWidth
                            size="small"
                            placeholder="Enter로 추가"
                            onKeyPress={(e) => {
                              if (e.key === 'Enter') {
                                const input = e.target as HTMLInputElement
                                handleAddIngredient(categoryIndex, itemIndex, input.value)
                                input.value = ''
                                e.preventDefault()
                              }
                            }}
                          />
                        </Box>
                      </Box>

                      {/* 오른쪽: 재료 Chip 목록 */}
                      <Box sx={{ flex: 1, display: 'flex', flexWrap: 'wrap', gap: 0.5, alignContent: 'flex-start' }}>
                        {item.ingredients?.map((ingredient, ingredientIndex) => (
                          <Chip
                            key={ingredientIndex}
                            label={ingredient}
                            size="small"
                            onDelete={() =>
                              handleRemoveIngredient(categoryIndex, itemIndex, ingredientIndex)
                            }
                          />
                        ))}
                      </Box>
                    </Box>
                  </Paper>
                </Grid>
              ))}
            </Grid>

            <Button
              startIcon={<Add />}
              onClick={() => handleAddItem(categoryIndex)}
              variant="outlined"
              size="small"
            >
              메뉴 아이템 추가
            </Button>
          </CardContent>
        </Card>
      ))}

      {/* 카테고리 추가 버튼 */}
      <Button
        startIcon={<Add />}
        onClick={handleAddCategory}
        variant="outlined"
        fullWidth
        sx={{ mb: 3 }}
      >
        카테고리 추가
      </Button>

      {/* 생성 버튼 */}
      <Button
        variant="contained"
        size="large"
        fullWidth
        onClick={handleGenerate}
        disabled={isLoading || !categories.some((c) => c.category_name && c.items.some((i) => i.name))}
        startIcon={isLoading ? <CircularProgress size={20} /> : <AutoAwesome />}
        sx={{ mb: 3 }}
      >
        {isLoading ? 'AI가 메뉴 설명과 이미지를 생성하고 있습니다... 잠시만 기다려주세요 (30초~1분)' : '메뉴판 생성하기'}
      </Button>

      {/* 로딩 중 안내 */}
      {isLoading && (
        <Alert severity="info" sx={{ mb: 3 }}>
          <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
            <Typography variant="body2" fontWeight="bold">
              메뉴판 생성 중입니다...
            </Typography>
            <Typography variant="body2">
              • AI가 각 메뉴의 설명을 작성하고 있습니다
            </Typography>
            <Typography variant="body2">
              • AI가 각 메뉴의 이미지를 생성하고 있습니다 (시간이 조금 걸릴 수 있습니다)
            </Typography>
            <Typography variant="body2">
              • 데이터베이스에 저장하고 있습니다
            </Typography>
            <Typography variant="caption" color="text.secondary" sx={{ mt: 1 }}>
              완료되면 자동으로 결과가 표시됩니다. 페이지를 새로고침하지 마세요!
            </Typography>
          </Box>
        </Alert>
      )}

      {/* 에러 메시지 */}
      {error && (
        <Alert severity="error" sx={{ mb: 3 }}>
          {error}
        </Alert>
      )}

      {/* 조회된 메뉴 */}
      {displayMenus && (
        <Card sx={{ mb: 3 }}>
          <CardContent>
            <Box sx={{ display: 'flex', alignItems: 'center', mb: 2 }}>
              <Restaurant sx={{ color: 'primary.main', mr: 1 }} />
              <Typography variant="h6">
                매장 ID {viewStoreId}번 메뉴판
              </Typography>
            </Box>

            {displayMenus.categories.map((category: any, index: number) => (
              <Box key={index} sx={{ mb: 3 }}>
                <Typography variant="h6" gutterBottom>
                  {category.name}
                </Typography>
                {category.description && (
                  <Typography variant="body2" color="text.secondary" gutterBottom>
                    {category.description}
                  </Typography>
                )}

                <Grid container spacing={2} sx={{ mt: 1 }}>
                  {category.items.map((item: any, itemIndex: number) => (
                    <Grid item xs={12} key={itemIndex}>
                      <Paper sx={{ p: 3, display: 'flex', gap: 3, alignItems: 'center' }}>
                        <MenuItemImage imageUrl={item.image_url} menuName={item.name} />

                        <Box sx={{ flex: 1, minWidth: 0 }}>
                          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 1.5 }}>
                            <Typography variant="h5" fontWeight="bold">
                              {item.name}
                            </Typography>
                            {item.is_ai_generated_image && (
                              <Chip label="AI 이미지" size="small" color="primary" />
                            )}
                          </Box>

                          {item.price && (
                            <Typography variant="h6" color="primary" fontWeight="bold" sx={{ mb: 2 }}>
                              {item.price.toLocaleString()}원
                            </Typography>
                          )}

                          {item.description && (
                            <Box>
                              <Typography variant="body1" color="text.secondary" sx={{ lineHeight: 1.7 }}>
                                {item.description}
                              </Typography>
                              {item.is_ai_generated_description && (
                                <Chip label="AI 설명" size="small" sx={{ mt: 1.5 }} color="secondary" />
                              )}
                            </Box>
                          )}
                        </Box>
                      </Paper>
                    </Grid>
                  ))}
                </Grid>
              </Box>
            ))}
          </CardContent>
        </Card>
      )}

      {/* 결과 */}
      {result && generatedStoreId && (
        <Card>
          <CardContent>
            <Box sx={{ display: 'flex', alignItems: 'center', mb: 3 }}>
              <CheckCircle sx={{ color: 'success.main', mr: 1, fontSize: 40 }} />
              <Typography variant="h4" fontWeight="bold">메뉴판 생성 완료!</Typography>
            </Box>

            <Alert severity="success" sx={{ mb: 4 }}>
              {result.data.total_categories}개 카테고리, {result.data.total_items}개 메뉴 생성 완료
              (소요시간: {result.data.generation_time.toFixed(2)}초)
            </Alert>

            <Divider sx={{ my: 3 }} />

            {/* URL 및 QR 코드 섹션 */}
            <Box sx={{ textAlign: 'center' }}>
              <Typography variant="h5" fontWeight="bold" gutterBottom sx={{ mb: 3 }}>
                AI 메뉴판 관리 페이지
              </Typography>

              {/* URL 표시 */}
              <Paper elevation={3} sx={{ p: 3, mb: 4, bgcolor: 'grey.50' }}>
                <Typography variant="body2" color="text.secondary" gutterBottom>
                  아래 URL로 접속하여 메뉴를 관리하세요
                </Typography>
                <Typography
                  variant="h6"
                  sx={{
                    mt: 1,
                    p: 2,
                    bgcolor: 'white',
                    borderRadius: 1,
                    fontFamily: 'monospace',
                    wordBreak: 'break-all'
                  }}
                >
                  {window.location.origin}/menu-board/{generatedStoreId}
                </Typography>
                <Button
                  variant="contained"
                  sx={{ mt: 2 }}
                  onClick={() => {
                    navigator.clipboard.writeText(`${window.location.origin}/menu-board/${generatedStoreId}`)
                    alert('URL이 복사되었습니다!')
                  }}
                >
                  URL 복사
                </Button>
              </Paper>

              {/* QR 코드 */}
              <Box sx={{ display: 'inline-block', p: 3, bgcolor: 'white', borderRadius: 2, boxShadow: 3 }}>
                <Typography variant="h6" gutterBottom>
                  QR 코드로 빠른 접속
                </Typography>
                <Box sx={{ mt: 2 }}>
                  <QRCodeCanvas
                    value={`${window.location.origin}/menu-board/${generatedStoreId}`}
                    size={256}
                    level="H"
                  />
                </Box>
                <Typography variant="body2" color="text.secondary" sx={{ mt: 2 }}>
                  QR 코드를 스캔하여 메뉴판에 바로 접속하세요
                </Typography>
              </Box>
            </Box>
          </CardContent>
        </Card>
      )}
    </Container>
  )
}

export default MenuGenerationPage
