import { useState } from 'react'
import {
  Box,
  Container,
  Typography,
  Card,
  CardContent,
  TextField,
  Button,
  Grid,
  IconButton,
  Alert,
  CircularProgress,
  Chip,
  Divider,
  Switch,
  FormControlLabel,
  Paper,
} from '@mui/material'
import {
  Add,
  Delete,
  Restaurant,
  AutoAwesome,
  CheckCircle,
} from '@mui/icons-material'
import { menuGenerationApi } from '@services/api'
import type {
  MenuCategoryCreate,
  MenuItemCreate,
  MenuGenerationResponse,
} from '@types/index'

function MenuGenerationPage() {
  // State
  const [storeId, setStoreId] = useState<string>('1')
  const [categories, setCategories] = useState<MenuCategoryCreate[]>([
    {
      category_name: '',
      category_description: '',
      items: [{ name: '', price: undefined, ingredients: [] }],
    },
  ])
  const [autoGenerateImages, setAutoGenerateImages] = useState(true)
  const [autoGenerateDescriptions, setAutoGenerateDescriptions] = useState(true)
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [result, setResult] = useState<MenuGenerationResponse | null>(null)

  // 카테고리 추가
  const handleAddCategory = () => {
    setCategories([
      ...categories,
      {
        category_name: '',
        category_description: '',
        items: [{ name: '', price: undefined, ingredients: [] }],
      },
    ])
  }

  // 카테고리 삭제
  const handleRemoveCategory = (categoryIndex: number) => {
    setCategories(categories.filter((_, index) => index !== categoryIndex))
  }

  // 카테고리 이름 변경
  const handleCategoryNameChange = (categoryIndex: number, value: string) => {
    const newCategories = [...categories]
    newCategories[categoryIndex].category_name = value
    setCategories(newCategories)
  }

  // 메뉴 아이템 추가
  const handleAddItem = (categoryIndex: number) => {
    const newCategories = [...categories]
    newCategories[categoryIndex].items.push({
      name: '',
      price: undefined,
      ingredients: [],
    })
    setCategories(newCategories)
  }

  // 메뉴 아이템 삭제
  const handleRemoveItem = (categoryIndex: number, itemIndex: number) => {
    const newCategories = [...categories]
    newCategories[categoryIndex].items = newCategories[categoryIndex].items.filter(
      (_, index) => index !== itemIndex
    )
    setCategories(newCategories)
  }

  // 메뉴 아이템 변경
  const handleItemChange = (
    categoryIndex: number,
    itemIndex: number,
    field: keyof MenuItemCreate,
    value: any
  ) => {
    const newCategories = [...categories]
    newCategories[categoryIndex].items[itemIndex] = {
      ...newCategories[categoryIndex].items[itemIndex],
      [field]: value,
    }
    setCategories(newCategories)
  }

  // 재료 추가
  const handleAddIngredient = (categoryIndex: number, itemIndex: number, ingredient: string) => {
    if (!ingredient.trim()) return

    const newCategories = [...categories]
    const currentIngredients = newCategories[categoryIndex].items[itemIndex].ingredients || []
    newCategories[categoryIndex].items[itemIndex].ingredients = [
      ...currentIngredients,
      ingredient.trim(),
    ]
    setCategories(newCategories)
  }

  // 재료 삭제
  const handleRemoveIngredient = (
    categoryIndex: number,
    itemIndex: number,
    ingredientIndex: number
  ) => {
    const newCategories = [...categories]
    const currentIngredients = newCategories[categoryIndex].items[itemIndex].ingredients || []
    newCategories[categoryIndex].items[itemIndex].ingredients = currentIngredients.filter(
      (_, index) => index !== ingredientIndex
    )
    setCategories(newCategories)
  }

  // 메뉴판 생성
  const handleGenerate = async () => {
    setIsLoading(true)
    setError(null)
    setResult(null)

    try {
      const response = await menuGenerationApi.generate({
        store_id: parseInt(storeId),
        categories,
        auto_generate_images: autoGenerateImages,
        auto_generate_descriptions: autoGenerateDescriptions,
      })

      setResult(response)
    } catch (err: any) {
      setError(err.message || '메뉴판 생성 중 오류가 발생했습니다.')
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <Container maxWidth="lg" sx={{ py: 4 }}>
      {/* 헤더 */}
      <Box sx={{ mb: 4, textAlign: 'center' }}>
        <Restaurant sx={{ fontSize: 48, color: 'primary.main', mb: 2 }} />
        <Typography variant="h3" gutterBottom fontWeight="bold">
          AI 메뉴판 생성
        </Typography>
        <Typography variant="h6" color="text.secondary">
          메뉴 카테고리와 아이템을 입력하면 AI가 자동으로 설명과 이미지를 생성합니다
        </Typography>
      </Box>

      {/* 설정 */}
      <Card sx={{ mb: 3 }}>
        <CardContent>
          <Typography variant="h6" gutterBottom>
            기본 설정
          </Typography>
          <Grid container spacing={2} alignItems="center">
            <Grid item xs={12} sm={4}>
              <TextField
                fullWidth
                label="매장 ID"
                type="number"
                value={storeId}
                onChange={(e) => setStoreId(e.target.value)}
              />
            </Grid>
            <Grid item xs={12} sm={4}>
              <FormControlLabel
                control={
                  <Switch
                    checked={autoGenerateDescriptions}
                    onChange={(e) => setAutoGenerateDescriptions(e.target.checked)}
                  />
                }
                label="AI 설명 자동 생성"
              />
            </Grid>
            <Grid item xs={12} sm={4}>
              <FormControlLabel
                control={
                  <Switch
                    checked={autoGenerateImages}
                    onChange={(e) => setAutoGenerateImages(e.target.checked)}
                  />
                }
                label="AI 이미지 자동 생성 (예정)"
              />
            </Grid>
          </Grid>
        </CardContent>
      </Card>

      {/* 카테고리 입력 */}
      {categories.map((category, categoryIndex) => (
        <Card key={categoryIndex} sx={{ mb: 3 }}>
          <CardContent>
            <Box sx={{ display: 'flex', alignItems: 'center', mb: 2 }}>
              <Typography variant="h6" sx={{ flexGrow: 1 }}>
                카테고리 {categoryIndex + 1}
              </Typography>
              {categories.length > 1 && (
                <IconButton
                  color="error"
                  onClick={() => handleRemoveCategory(categoryIndex)}
                >
                  <Delete />
                </IconButton>
              )}
            </Box>

            <TextField
              fullWidth
              label="카테고리 이름 (예: 파스타, 스테이크)"
              value={category.category_name}
              onChange={(e) => handleCategoryNameChange(categoryIndex, e.target.value)}
              sx={{ mb: 2 }}
            />

            <Divider sx={{ my: 2 }} />

            {/* 메뉴 아이템 */}
            {category.items.map((item, itemIndex) => (
              <Paper key={itemIndex} sx={{ p: 2, mb: 2, bgcolor: 'grey.50' }}>
                <Box sx={{ display: 'flex', alignItems: 'center', mb: 2 }}>
                  <Typography variant="subtitle1" sx={{ flexGrow: 1 }}>
                    메뉴 {itemIndex + 1}
                  </Typography>
                  {category.items.length > 1 && (
                    <IconButton
                      size="small"
                      color="error"
                      onClick={() => handleRemoveItem(categoryIndex, itemIndex)}
                    >
                      <Delete />
                    </IconButton>
                  )}
                </Box>

                <Grid container spacing={2}>
                  <Grid item xs={12} sm={6}>
                    <TextField
                      fullWidth
                      label="메뉴 이름 (필수)"
                      value={item.name}
                      onChange={(e) =>
                        handleItemChange(categoryIndex, itemIndex, 'name', e.target.value)
                      }
                      required
                    />
                  </Grid>
                  <Grid item xs={12} sm={6}>
                    <TextField
                      fullWidth
                      label="가격"
                      type="number"
                      value={item.price || ''}
                      onChange={(e) =>
                        handleItemChange(
                          categoryIndex,
                          itemIndex,
                          'price',
                          e.target.value ? parseFloat(e.target.value) : undefined
                        )
                      }
                    />
                  </Grid>
                  <Grid item xs={12}>
                    <Box>
                      <Typography variant="body2" color="text.secondary" gutterBottom>
                        재료 (Enter로 추가)
                      </Typography>
                      <TextField
                        fullWidth
                        size="small"
                        placeholder="재료 입력 후 Enter"
                        onKeyPress={(e) => {
                          if (e.key === 'Enter') {
                            const input = e.target as HTMLInputElement
                            handleAddIngredient(categoryIndex, itemIndex, input.value)
                            input.value = ''
                            e.preventDefault()
                          }
                        }}
                      />
                      <Box sx={{ mt: 1, display: 'flex', flexWrap: 'wrap', gap: 0.5 }}>
                        {item.ingredients?.map((ingredient, ingredientIndex) => (
                          <Chip
                            key={ingredientIndex}
                            label={ingredient}
                            size="small"
                            onDelete={() =>
                              handleRemoveIngredient(categoryIndex, itemIndex, ingredientIndex)
                            }
                          />
                        ))}
                      </Box>
                    </Box>
                  </Grid>
                </Grid>
              </Paper>
            ))}

            <Button
              startIcon={<Add />}
              onClick={() => handleAddItem(categoryIndex)}
              variant="outlined"
              size="small"
            >
              메뉴 아이템 추가
            </Button>
          </CardContent>
        </Card>
      ))}

      {/* 카테고리 추가 버튼 */}
      <Button
        startIcon={<Add />}
        onClick={handleAddCategory}
        variant="outlined"
        fullWidth
        sx={{ mb: 3 }}
      >
        카테고리 추가
      </Button>

      {/* 생성 버튼 */}
      <Button
        variant="contained"
        size="large"
        fullWidth
        onClick={handleGenerate}
        disabled={isLoading || !categories.some((c) => c.category_name && c.items.some((i) => i.name))}
        startIcon={isLoading ? <CircularProgress size={20} /> : <AutoAwesome />}
        sx={{ mb: 3 }}
      >
        {isLoading ? '메뉴판 생성 중...' : '메뉴판 생성하기'}
      </Button>

      {/* 에러 메시지 */}
      {error && (
        <Alert severity="error" sx={{ mb: 3 }}>
          {error}
        </Alert>
      )}

      {/* 결과 */}
      {result && (
        <Card>
          <CardContent>
            <Box sx={{ display: 'flex', alignItems: 'center', mb: 2 }}>
              <CheckCircle sx={{ color: 'success.main', mr: 1 }} />
              <Typography variant="h6">생성 완료!</Typography>
            </Box>

            <Alert severity="success" sx={{ mb: 2 }}>
              {result.data.total_categories}개 카테고리, {result.data.total_items}개 메뉴 생성 완료
              (소요시간: {result.data.generation_time.toFixed(2)}초)
            </Alert>

            {result.data.categories.map((category, index) => (
              <Box key={index} sx={{ mb: 3 }}>
                <Typography variant="h6" gutterBottom>
                  {category.name}
                </Typography>
                {category.description && (
                  <Typography variant="body2" color="text.secondary" gutterBottom>
                    {category.description}
                  </Typography>
                )}

                <Grid container spacing={2} sx={{ mt: 1 }}>
                  {category.items.map((item, itemIndex) => (
                    <Grid item xs={12} sm={6} md={4} key={itemIndex}>
                      <Paper sx={{ p: 2 }}>
                        <Typography variant="subtitle1" fontWeight="bold">
                          {item.name}
                        </Typography>
                        {item.price && (
                          <Typography variant="body2" color="primary">
                            {item.price.toLocaleString()}원
                          </Typography>
                        )}
                        {item.description && (
                          <Typography variant="body2" color="text.secondary" sx={{ mt: 1 }}>
                            {item.description}
                            {item.is_ai_generated_description && (
                              <Chip label="AI 생성" size="small" sx={{ ml: 1 }} />
                            )}
                          </Typography>
                        )}
                      </Paper>
                    </Grid>
                  ))}
                </Grid>
              </Box>
            ))}
          </CardContent>
        </Card>
      )}
    </Container>
  )
}

export default MenuGenerationPage
